DROP TABLE `activity_logs`;--> statement-breakpoint
DROP TABLE `ai_chat_messages`;--> statement-breakpoint
DROP TABLE `ai_corrections`;--> statement-breakpoint
DROP TABLE `company_settings`;--> statement-breakpoint
DROP TABLE `custom_field_definitions`;--> statement-breakpoint
DROP TABLE `deal_stages`;--> statement-breakpoint
DROP TABLE `deal_attachments`;--> statement-breakpoint
DROP TABLE `deal_contacts`;--> statement-breakpoint
DROP TABLE `deal_custom_fields`;--> statement-breakpoint
DROP TABLE `deal_documents`;--> statement-breakpoint
DROP TABLE `deal_messages`;--> statement-breakpoint
DROP TABLE `deals`;--> statement-breakpoint
DROP TABLE `documents`;--> statement-breakpoint
DROP TABLE `financial_transactions`;--> statement-breakpoint
DROP TABLE `installations`;--> statement-breakpoint
DROP TABLE `material_prices`;--> statement-breakpoint
DROP TABLE `process_templates`;--> statement-breakpoint
DROP TABLE `production_stages`;--> statement-breakpoint
DROP TABLE `production_tasks`;--> statement-breakpoint
DROP TABLE `project_items`;--> statement-breakpoint
DROP TABLE `project_stages`;--> statement-breakpoint
DROP TABLE `projects`;--> statement-breakpoint
DROP TABLE `role_permissions`;--> statement-breakpoint
DROP TABLE `roles`;--> statement-breakpoint
DROP TABLE `sales_pipelines`;--> statement-breakpoint
DROP TABLE `stage_dependencies`;--> statement-breakpoint
DROP TABLE `stage_messages`;--> statement-breakpoint
DROP TABLE `task_checklist_items`;--> statement-breakpoint
DROP TABLE `task_comments`;--> statement-breakpoint
DROP TABLE `tasks`;--> statement-breakpoint
DROP TABLE `template_dependencies`;--> statement-breakpoint
DROP TABLE `template_stage_attachments`;--> statement-breakpoint
DROP TABLE `template_stages`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `warehouse_items`;--> statement-breakpoint
DROP TABLE `warehouse_reservations`;--> statement-breakpoint
DROP TABLE `warehouse_transactions`;